### ISSUE TITLE
Guidance on Running the Project with CARLA 0.9.13 without Docker

### ISSUE THREAD

**Issue by i-kj** [lasuomela/carla_vloc_benchmark#8]
Hello @lasuomela,

I am very interested in your CARLA Visual Localization Benchmark project and I have already emulated it on my local machine. However, I want to learn more and I am facing a couple of challenges and would really appreciate your guidance.

CARLA Version: I have CARLA 0.9.13 source-built on my machine and would prefer to use this version instead of the 0.9.12 version that the project was originally developed with. Would it be possible to guide me on any necessary modifications to the project code to ensure compatibility with CARLA 0.9.13 so I can experiment by adding custom models?

Avoiding Docker: I noticed that the project setup is dockerized for ease of use. However, I would like to set up and run the project without using Docker on my Ubuntu PC. My reason for this preference is to gain a deeper understanding of the environment setup and dependencies, which is a part of my learning process. I believe setting up the project manually will provide a hands-on experience and a better understanding of how all components interact with each other.

I have already cloned the repository and attempted to set up the environment manually, but I am unsure if I am on the right track, especially with the change in CARLA version. Your expertise and advice on this would be extremely valuable.

Additionally, I must mention that your project is serving as a valuable learning resource for me. The practical insights and the structure of your project are significantly aiding my learning journey in this domain.

Thank you very much for your time and assistance. I am really excited about the potential of this project and am eager to get it up and running on my setup.

Best regards,
KJ

**Comment by lasuomela** [comment]
Hello,

Carla 0.9.13 might not be compatible with the carla-ros-bridge or carla-scenario-runner versions used in this benchmark. Especially the scenario runner version used in this benchmark contain improvements that were never merged into the main repository because of the inactivity of repo maintainers (see https://github.com/carla-simulator/scenario_runner/issues/832), so switching scenario runner version might be very tricky. I suggest against it, but feel free to try.

If you want to install the benchmark environment locally on your machine, you can follow the docker build scripts and Dockerfiles to find which packages are installed in which order. Unfortunately I will not be able to provide hands-on guidance.

Br,
Lauri
