### ISSUE TITLE
Assistance Required to Spawn Audi A2 Instead of Tesla Model 3 in CARLA

### ISSUE THREAD

**Issue by i-kj** [lasuomela/carla_vloc_benchmark#9]
Hello Lasuomela,
I am working with CARLA (version 9.12) and I've run into an issue when trying to change the default vehicle from the Tesla Model 3 to an Audi A2. Despite updating the configuration file, the simulator continues to spawn the Tesla Model 3.

Here are the steps I've taken so far:
1. Modified the objects.json files, changing the vehicle type to what I believed was the correct type for the Audi A2.
   ```
    {
            "type": "vehicle.audi.a2",
            "id": "ego_vehicle",
            "sensors":
            [
                ```
    2. Checked that the ROS launch file is pointing to the updated objects.json file.
    3. Restarted the CARLA server post-configuration changes to prevent any caching issues.
    4. Looked through the documentation for any steps that I might have missed regarding vehicle spawning and configuration.

Unfortunately, the log still shows that the Tesla Model 3 is being spawned:

```[2023.11.06-16.21.47:741][236]LogCarla: Spawning actor 'vehicle.tesla.model3'```

Could you provide guidance or point out what I might be doing incorrectly? If there are specific steps to follow when changing the default vehicle, I would appreciate your detailed advice.

Thank you for your support.

**Comment by lasuomela** [comment]
Hello,

I have not tried changing the default vehicle since it wasn't relevant for the benchmark. To my understanding it should work by changing the vehicle model in [objects.json](https://github.com/lasuomela/carla_vloc_benchmark/blob/main/carla_vloc_benchmark/carla_visual_navigation/config/objects.json)

Did you rebuild the ros package using `colcon build` after modifying objects.json? If yes, this sounds more like a problem with the carla ros bridge than with this benchmark.

**Comment by i-kj** [comment]
Thank you lasuomela. It worked.
